name: sort_json
description: A tool to sort JSON files alphabetically while prioritizing specific keys.
version: 1.0.2
repository: https://github.com/HeronKyaw/sort_json
license: MIT
executables:
  sort_json: sort_json

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - json
  - cli
  - sorting
  - dart
