name: sort_json
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/HeronKyaw/sort_json

executables:
  sort_json: sort_json

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
